[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"
keyfile = "keys.toml"


[eid-mw]
source = "regex"
regex = "[\\d.]+\\.\\d*"
url = "https://dist.eid.belgium.be/continuous/sources"

[fvwm]
source = "github"
github = "fvwmorg/fvwm"
use_latest_release = true

[gnubg]
source = "git"
git = "https://git.savannah.gnu.org/git/gnubg.git"
prefix = "release-"
from_pattern = "(\\d+)_(\\d+)_(\\d+)"
to_pattern = "\\1.\\2.\\3 "

[gnubg-git]
source = "git"
git = "https://git.savannah.gnu.org/git/gnubg.git"
use_commit = true

[gnucobol]
source = "regex"
regex = "The current release, version [\\d.]+\\.\\d+"
url = "https://gnucobol.sourceforge.io/"

[gregorio]
source = "github"
github = "gregorio-project/gregorio"
use_latest_release = true

[gtkglext]
source = "regex"
regex = "([\\d.]+\\.\\d+).tar.gz"
url = "https://download.gnome.org/sources/gtkglext/1.2/"

[libcs50]
source = "github"
github = "cs50/libcs50"
use_latest_release = true

[libcs50-git]
source = "github"
github = "cs50/libcs50"

[libstroke]
source = "regex"
regex = "([\\d.]+\\.\\d+).tar.gz"
url = "https://sources.archlinux.org/other/packages/libstroke/"

[openarc]
source = "github"
github = "flowerysong/openarc"
use_latest_release = true

[openarc-git]
source = "github"
github = "flowerysong/openarc"
use_commit = true

[openbgpd]
source = "github"
github = "openbgpd-portable/openbgpd-portable"
use_latest_tag = true

[python-miltertest]
source = "pypi"
pypi = "miltertest"

[python-pyalsaaudio]
source = "pypi"
pypi = "pyalsaaudio"

[solfege]
source = "regex"
regex = "([\\d.]+\\.\\d+).tar.gz"
#url = "https://sourceforge.net/projects/solfege/files/solfege-unstable/"
url = "https://sourceforge.net/projects/solfege/rss?path=/solfege-unstable"

[spleen-font]
source = "github"
github = "fcambus/spleen"
use_latest_release = true

[usb_resetter]
source = "github"
github = "netinvent/usb_resetter"
use_latest_release = true
